Repository gipplab/cs-insights-backend, pull requests merged in 2022-08, with the labels that each got.

#77 Add lda topics endpoints
  .env.development
  .github/workflows/main.yml
  .github/workflows/release.yml
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/app/controllers/frontend/papers.ts
  src/app/controllers/frontend/queryUtils.ts
  src/app/controllers/frontend/topics.ts
  src/app/controllers/index.ts
  src/types.ts
  test/controllers/affiliations.ts
  test/controllers/frontend/papers.ts
  test/controllers/frontend/testdata.ts
  test/controllers/frontend/topics.ts
Labels: feature

#80 Add quartiles endpoints for citations
  src/app/controllers/frontend/citations.ts
  src/app/controllers/frontend/queryUtils.ts
  src/app/models/schemas.ts
  test/controllers/frontend/citations.ts
Labels: enhancement

#89 💲 Add caching mechanism for frontend routes
  package-lock.json
  package.json
  src/app/controllers/frontend/authors.ts
  src/app/controllers/frontend/citations.ts
  src/app/controllers/frontend/fieldsOfStudy.ts
  src/app/controllers/frontend/papers.ts
  src/app/controllers/frontend/publishers.ts
  src/app/controllers/frontend/topics.ts
  src/app/controllers/frontend/typesOfPaper.ts
  src/app/controllers/frontend/venues.ts
  src/config/default.ts
  src/config/interfaces.ts
  test/controllers/frontend/authors.ts
  test/controllers/frontend/citations.ts
  test/controllers/frontend/fieldsOfStudy.ts
  test/controllers/frontend/papers.ts
  test/controllers/frontend/publishers.ts
  test/controllers/frontend/typesOfPaper.ts
  test/controllers/frontend/venues.ts
Labels: feature

#92 ↪ New pull request labels for release changelog
  .github/workflows/release.yml
  pr_config.json
Labels: documentation

#93 Replace /fe/papers/quartiles with previous function
  src/app/controllers/frontend/papers.ts
Labels: perf
